#!/bin/bash

# Script to clear Cloudflare D1 database and reset migrations
# Usage: ./scripts/clear-database.sh [local|remote]

ENV=${1:-local}

# Function to execute SQL command and ignore errors
execute_sql() {
  local env_flag=$1
  local sql=$2
  wrangler d1 execute D1 $env_flag --command "$sql" 2>/dev/null || true
}

if [ "$ENV" = "remote" ]; then
  echo "Clearing remote D1 database..."
  ENV_FLAG="--remote"
else
  echo "Clearing local D1 database..."
  ENV_FLAG="--local"
fi

# Drop all indexes first
echo "Dropping all indexes..."
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS users_sessions_order_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS users_sessions_parent_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS users_updated_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS users_created_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS users_email_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS media_updated_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS media_created_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS media_filename_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_populated_authors_order_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_populated_authors_parent_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_hero_image_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_category_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_meta_meta_image_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_slug_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_updated_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_created_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts__status_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_rels_order_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_rels_parent_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_rels_path_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_rels_posts_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS posts_rels_users_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_version_populated_authors_order_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_version_populated_authors_parent_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_parent_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_version_version_hero_image_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_version_version_category_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_version_meta_version_meta_image_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_version_version_slug_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_version_version_updated_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_version_version_created_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_version_version__status_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_created_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_updated_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_latest_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_autosave_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_rels_order_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_rels_parent_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_rels_path_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_rels_posts_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS _posts_v_rels_users_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS categories_slug_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS categories_updated_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS categories_created_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_kv_key_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_jobs_log_order_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_jobs_log_parent_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_jobs_completed_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_jobs_total_tried_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_jobs_has_error_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_jobs_task_slug_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_jobs_queue_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_jobs_wait_until_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_jobs_processing_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_jobs_updated_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_jobs_created_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_locked_documents_global_slug_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_locked_documents_updated_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_locked_documents_created_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_locked_documents_rels_order_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_locked_documents_rels_parent_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_locked_documents_rels_path_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_locked_documents_rels_users_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_locked_documents_rels_media_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_locked_documents_rels_posts_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_locked_documents_rels_categories_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_preferences_key_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_preferences_updated_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_preferences_created_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_preferences_rels_order_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_preferences_rels_parent_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_preferences_rels_path_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_preferences_rels_users_id_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_migrations_updated_at_idx;"
execute_sql "$ENV_FLAG" "DROP INDEX IF EXISTS payload_migrations_created_at_idx;"

# Drop all tables (order matters due to foreign keys)
echo "Dropping all tables..."
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS payload_migrations;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS payload_preferences_rels;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS payload_preferences;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS payload_locked_documents_rels;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS payload_locked_documents;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS payload_jobs_log;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS payload_jobs;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS payload_kv;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS _posts_v_rels;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS _posts_v;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS _posts_v_version_populated_authors;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS posts_populated_authors;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS posts_rels;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS posts;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS categories;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS media;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS users_sessions;"
execute_sql "$ENV_FLAG" "DROP TABLE IF EXISTS users;"

echo "Database cleared. Now run: pnpm run payload migrate"

